//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Works
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment_Works()
        {
            this.Replys_Work = new HashSet<Replys_Work>();
        }
    
        public int CommentID_Works { get; set; }
        public string Com_Content { get; set; }
        public System.DateTime Com_Date { get; set; }
        public int User_Id { get; set; }
        public int Work_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Works Works { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replys_Work> Replys_Work { get; set; }
    }
}
