//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Product
    {
        public int Comment_Product_ID { get; set; }
        public int UserID { get; set; }
        public string Com_Content { get; set; }
        public System.DateTime Com_Data { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Praise_Num { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
