//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LessProEntities : DbContext
    {
        public LessProEntities()
            : base("name=LessProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add_Course> Add_Course { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Collect_Work> Collect_Work { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Comment_Course> Comment_Course { get; set; }
        public virtual DbSet<Comment_Product> Comment_Product { get; set; }
        public virtual DbSet<Comment_Works> Comment_Works { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Course_Class> Course_Class { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_Detail> Order_Detail { get; set; }
        public virtual DbSet<Order_Product_Detail> Order_Product_Detail { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Praise_Product> Praise_Product { get; set; }
        public virtual DbSet<Praised> Praised { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Image> Product_Image { get; set; }
        public virtual DbSet<Product_Norms> Product_Norms { get; set; }
        public virtual DbSet<Product_Reply> Product_Reply { get; set; }
        public virtual DbSet<Replys> Replys { get; set; }
        public virtual DbSet<Replys_Course> Replys_Course { get; set; }
        public virtual DbSet<Replys_Work> Replys_Work { get; set; }
        public virtual DbSet<Return_Product> Return_Product { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Works> Works { get; set; }
    }
}
