//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Product_Detail = new HashSet<Order_Product_Detail>();
        }
    
        public int Order_ID { get; set; }
        public string Order_State { get; set; }
        public System.DateTime Order_Time { get; set; }
        public System.DateTime Pay_Time { get; set; }
        public int UserID { get; set; }
        public string User_Remarks { get; set; }
        public int Adress_ID { get; set; }
        public int Order_Detail_ID { get; set; }
        public int Cart_ID { get; set; }
        public int Order_Product_Detail_ID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Order_Detail Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product_Detail> Order_Product_Detail { get; set; }
        public virtual User User { get; set; }
    }
}
