//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Product_ID { get; set; }
        public int Order_Detail_ID { get; set; }
        public System.DateTime Pay_Time { get; set; }
        public string Users_Remarks { get; set; }
        public string Adress { get; set; }
        public int Pro_Num { get; set; }
        public int Pro_Norm_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Norms Product_Norms { get; set; }
        public virtual User User { get; set; }
    }
}
