//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Reply
    {
        public int Reply_Product_ID { get; set; }
        public int Comment_Product_ID { get; set; }
        public string Rep_Content { get; set; }
        public string Rep_Data { get; set; }
        public int Rep_UserID { get; set; }
        public int Rep_to_UserID { get; set; }
    
        public virtual Comment_Product Comment_Product { get; set; }
        public virtual User User { get; set; }
    }
}
