//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replys_Course
    {
        public int ReplyID_Course { get; set; }
        public int Com_Id_Course { get; set; }
        public string Rep_Content { get; set; }
        public string Rep_Date { get; set; }
        public int Rep_UserId { get; set; }
        public int Rep_To_UserId { get; set; }
        public int Rep_Type { get; set; }
        public int Rep_Praise_Num { get; set; }
    
        public virtual Comment_Course Comment_Course { get; set; }
        public virtual User User { get; set; }
    }
}
