//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Product
    {
        public int Return_Product_ID { get; set; }
        public int Order_Detail_ID { get; set; }
        public string Delivery_Company { get; set; }
        public int UserID { get; set; }
    
        public virtual Order_Detail Order_Detail { get; set; }
        public virtual User User { get; set; }
    }
}
