//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public string VideoName { get; set; }
        public int Teacher_Id { get; set; }
        public int ClassId { get; set; }
        public string Video_Content { get; set; }
    
        public virtual Course_Class Course_Class { get; set; }
    }
}
