//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CourseAllTable
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMineType { get; set; }
        public System.DateTime Course_Time { get; set; }
        public int TeacherId { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Value { get; set; }
        public int CourseTypeID { get; set; }
        public string CourseTypeName { get; set; }
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int VideoID { get; set; }
        public string VideoName { get; set; }
    }
}
