//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Guanzhu
    {
        public int Guanzhu_id { get; set; }
        public int UserA { get; set; }
        public int UserB { get; set; }
        public string UserName { get; set; }
        public string UserName1 { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Password { get; set; }
        public string Password1 { get; set; }
        public string Sex { get; set; }
        public string Sex1 { get; set; }
        public string RealName { get; set; }
        public string RealName1 { get; set; }
        public string ImageMineType { get; set; }
        public string ImageMineType1 { get; set; }
        public byte[] ImageData { get; set; }
        public byte[] ImageData1 { get; set; }
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string teacherpass { get; set; }
        public string ImageHead { get; set; }
        public string Phone2 { get; set; }
    }
}
